server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;

  include /etc/nginx/mime.types;
  types {
    application/javascript js mjs;
    text/css               css;
    text/html              html htm;
    application/json       json;
    image/svg+xml          svg svgz;
    image/webp             webp;
    image/avif             avif;
    image/x-icon           ico;
    font/woff2             woff2;
    font/woff              woff;
    application/wasm       wasm;
  }
  default_type application/octet-stream;

  location /healthz {
    access_log off;
    return 200 'OK';
    add_header Content-Type text/plain;
  }

  location / {
    try_files $uri $uri.html $uri/ =404;
  }
  
  error_page 404 /404.html;

  location ~* \.(html|css|js)$ { add_header Cache-Control "no-cache"; }
  location ~* \.(jpg|jpeg|png|webp|gif|svg|avif|ico|woff2?)$ { expires 7d; add_header Cache-Control "public"; }
  
  gzip on;
  gzip_types text/css application/javascript image/svg+xml application/json;
}
